# This file is machine-generated - editing it directly is not advised

[[IntelITT]]
git-tree-sha1 = "5cafd2bbc2f8ad6ac6f1fc2b0264250b0796185f"
repo-rev = "master"
repo-url = "../.."
uuid = "4a09e4cd-0946-40c7-bf0b-7fff0296c535"
version = "0.1.0"
